apiVersion: v1
kind: Service
metadata:
  name: churnmlproject-service
spec:
  selector:
    app: churnmlproject
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8501 
  